version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          name: Restore Yarn cache
          keys: ['yarn-v1-{{ checksum "yarn.lock" }}']
      - run:
          name: Install dependencies
          command: "yarn install --frozen-lockfile --cache-folder ~/.cache/yarn"
      - save_cache:
          name: Save Yarn cache
          key: 'yarn-v1-{{ checksum "yarn.lock" }}'
          paths: ["~/.cache/yarn"]
      - run: yarn lint
      - run: yarn test
workflows:
  test:
    jobs:
      - test
