version: 2.1
orbs:
  node: circleci/node@5.0.1
jobs:
  dummy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node -v
      - run: npm -v
      - run: yarn -v
workflows:
  dummy:
    jobs:
      - dummy:
          filters:
            branches:
              only: dummy
