version: 2.1
orbs:
  node: circleci/node@5.0.2
commands:
  git_checkout_and_config:
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["dd:f4:c2:d0:4f:dc:64:85:73:8f:2c:b9:5d:1c:63:9c"]
      - run:
          name: Configure Git
          command: |
            git config user.name bot
            git config user.email bot@webdino.org
  yarn_install_with_cache:
    steps:
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - "yarn-v1-main"
      - run:
          name: Install dependencies
          command: "yarn install --frozen-lockfile --cache-folder ~/.cache/yarn"
      - save_cache:
          name: Save Yarn cache
          key: "yarn-v1-main"
          paths:
            - ~/.cache/yarn
            - ~/.cache/ms-playwright
jobs:
  main:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - git_checkout_and_config
      - node/install:
          install-yarn: true
          # NOTE: Node.js v18.7.0 で @webdino/profile-model:test に失敗する問題 (#315) ので Node.js v16.17.0 を使う
          node-version: "16.17.0"
      - yarn_install_with_cache
      - run: yarn format
      - run:
          name: Commit
          command: |
            if git commit -am 'bot: format [skip ci]'; then
              git push origin HEAD:"$CIRCLE_BRANCH"
            fi
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - store_artifacts:
          path: apps/web-ext/web-ext-artifacts
      - run:
          name: E2Eテストの準備
          command: sudo apt-get install -y fonts-noto-cjk
      - run:
          name: E2E tests
          shell: /bin/bash -e
          command: yarn e2e
      - store_artifacts:
          path: apps/web-ext/screenshots
workflows:
  test:
    jobs: [main]
