version: 2.1
workflows:
  test:
    jobs:
      - main
jobs:
  main:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - setup
      - format
      - lint
      - build
      - test
      - e2e
orbs:
  node: circleci/node@5.1.0
commands:
  setup:
    steps:
      - git_checkout_and_config
      - node/install:
          install-yarn: true
          node-version: lts
      - yarn_install_with_cache
      - playwright_install
      - wordpress_up
  format:
    steps:
      - run: yarn format
      - wordpress_format
      - run:
          name: Commit
          command: |
            if git commit -am 'bot: format [skip ci]'; then
              git push origin HEAD:"$CIRCLE_BRANCH"
            fi
  lint:
    steps:
      - run: yarn lint
      - wordpress_lint
  build:
    steps:
      - run: yarn build
      - store_artifacts:
          path: apps/web-ext/web-ext-artifacts
  test:
    steps:
      - run: yarn test
      - wordpress_test
  e2e:
    steps:
      - run:
          name: E2Eテストの準備
          command: sudo apt-get install -y fonts-noto-cjk
      - run:
          name: E2E tests
          shell: /bin/bash -e
          command: yarn e2e
      - store_artifacts:
          path: apps/web-ext/screenshots

  # Helper commands
  git_checkout_and_config:
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["3a:70:44:f3:42:83:3a:26:09:50:b5:42:6d:2c:87:82"]
      - run:
          name: Configure Git
          command: |
            git config user.name bot
            git config user.email bot@webdino.org
  yarn_install_with_cache:
    steps:
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - "yarn-v1-main"
      - run:
          name: Install dependencies
          command: "yarn install --frozen-lockfile --cache-folder ~/.cache/yarn"
      - save_cache:
          name: Save Yarn cache
          key: "yarn-v1-main"
          paths:
            - ~/.cache/yarn
            - ~/.cache/ms-playwright
  playwright_install:
    steps:
      - run: npx playwright install --with-deps
  wordpress_up:
    steps:
      - restore_cache:
          name: Restore Composer cache
          keys:
            - composer-v2-main-{{ checksum "packages/wordpress/composer.lock" }}
      - run:
          name: Install WordPress dependencies
          command: |
            cp .env.development .env
            docker compose up -d
            docker compose exec -w /var/www/html/wp-content/plugins/profile wordpress composer install
          working_directory: packages/wordpress
      - save_cache:
          name: Save Composer cache
          key: composer-v2-main-{{ checksum "packages/wordpress/composer.lock" }}
          paths:
            - packages/wordpress/vendor
  wordpress_format:
    steps:
      - run:
          name: composer run format
          command: docker compose exec -w /var/www/html/wp-content/plugins/profile wordpress composer run format
          working_directory: packages/wordpress
  wordpress_lint:
    steps:
      - run:
          name: composer run lint
          command: docker compose exec -w /var/www/html/wp-content/plugins/profile wordpress composer run lint
          working_directory: packages/wordpress
  wordpress_test:
    steps:
      - run:
          name: composer run test
          command: docker compose exec -w /var/www/html/wp-content/plugins/profile wordpress composer run test
          working_directory: packages/wordpress
