name: release
run-name: "${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Increment "major", "minor", "patch", "prerelease" or "pre*" version; or specify version'
        default: prerelease
        required: true
jobs:
  main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: "./.github/actions/setup"
      - name: Bump version
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          pnpm exec lerna version --yes "${{ github.event.inputs.version }}"
      - name: Build
        uses: "./.github/actions/build"
        with:
          BASIC_AUTH_CREDENTIALS: ${{ secrets.BASIC_AUTH_CREDENTIALS }}
          REGISTRY_OPS: ${{ secrets.REGISTRY_OPS }}
      - name: Build for WordPress plugin
        uses: "./.github/actions/wordpress_build"
      - name: Publish Packages
        run: pnpm publish --access restricted --recursive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event.inputs.version != 'prerelease'
        name: Prerelease
        run: |
          pnpm exec lerna version --force-publish --yes prerelease
